routes:

collections:
  /:
    permalink: /es/{slug}/
    data: page.index
    template: home
    filter: 'tag:-hash-en'
  /en/:
    permalink: /en/{slug}/
    data: page.index-en
    template: home
    filter: 'tag:hash-en'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
